# Author: Naveen Duhan
name: deepnec2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9,<3.12
  - transdecoder
  - pip
  - pip:
    - numpy>=1.23.5,<2.0
    - pandas>=1.4.0
    - biopython>=1.79
    - tensorflow==2.16.2
    - torch>=2.0.0
    - transformers>=4.30.0
    - matplotlib>=3.5.0
    - seaborn>=0.11.0
