# Author: Naveen Duhan
name: deepnec2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8,<3.13
  - diamond>=2.0.0
  - blast
  - transdecoder
  - pip
  - pip:
    - numpy>=1.23.5,<2.0
    - pandas
    - biopython
    - tensorflow==2.16.2
    - torch
    - transformers
